1.将下面的字典创建为DataFrame\
2.提取含有字符串"Python"的行\
3.输出df的所有列名\
4.修改第二列列名为"popularity"\
5.统计grammer列中每种编程语言出现的次数

In [7]:
import numpy as np
import pandas as pd

**1.将下面的字典创建为DataFrame**

In [8]:
data = {
    "grammer":['Python','C','Java','GO',np.nan,'SQL','PHP','Python'],
    "score":[1,2,np.nan,4,5,6,7,10]
}

In [9]:
df = pd.DataFrame(data)

In [10]:
df

  grammer  score
0  Python    1.0
1       C    2.0
2    Java    NaN
3      GO    4.0
4     NaN    5.0
5     SQL    6.0
6     PHP    7.0
7  Python   10.0

**2.提取含有字符串"Python"的行**

In [17]:
df[df['grammer']=='Python']

  grammer  score
0  Python    1.0
7  Python   10.0